name: build

on:
  pull_request:

jobs:
  buildnpm:
    name: npm
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@v2
    -
      name: npm install
      run: npm install
    -
      name: build
      run: npm run build

